### ISSUE TITLE
Failed to load the build-makepbo package

### ISSUE THREAD

**Issue by Doggvir** [idleberg/atom-build-makepbo#1]
Installed via git and getting this error when opening atom.

Unexpected string in C:\Users\Doggv.atom\packages\build-makepbo\package.json

`SyntaxError: Unexpected string
    at Object.parse (native)
    at parseObject (C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\season\lib\cson.js:54:19)
    at parseContentsSync (C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\season\lib\cson.js:68:16)
    at Object.module.exports.readFileSync (C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\season\lib\cson.js:170:14)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:700:29)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:423:36)
    at C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\Doggv\AppData\Local\atom\app-1.7.4\resources\app.asar\src\atom-environment.js:743:28
  at C:\Users\Doggv\.atom\packages\build-makepbo\package.json:1:1`

**Comment by Doggvir** [comment]
Fixed syntax error and created a PR: #2

**Comment by idleberg** [comment]
Are you the guy who asked about `makepbo` on the Atom forum? I only put this together because it was an easy thing to do. I don't even know what this does. If you think of it as being useful, I can publish it.

**Comment by Doggvir** [comment]
No but I did find this through that thread. I believe makepbo is (somehow) broken and the author has chosen to end support/updates unless you purchase it for $35. I was hoping someone would be able to get this to work.
